title: Regis Kopper
author: Regis Kopper
email: rkopper@iastate.edu
description: Assistant Professor of Computer Science at Iowa State University, Director of the Interactive Realities Laboratory.
# url: "https://www.regiskopper.com"
url: "/irlab-policies"
baseurl: ""
remote_theme: academicpages/academicpages
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

paginate: 10
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

nav:
  - title: Home
    url: /
  - title: Publications
    url: /publications/
  - title: Teaching
    url: /teaching/
  - title: IRLab
    url: /ms-phd-requirements/

collections:
  publications:
    output: true
    permalink: /publications/:title/
