title: Regis Kopper
author: Regis Kopper
email: rkopper@iastate.edu
description: Assistant Professor of Computer Science at Iowa State University, Director of the Interactive Realities Laboratory.
url: "https://interactive-realities-lab.github.io"
baseurl: "/irlab-policies"
remote_theme: academicpages/academicpages
plugins:
  - jekyll-remote-theme
